[project]
name = "gui-renamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygobject>=3.52.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pygobject-stubs>=2.13.0",
    "ruff>=0.12.7",
]
